[2025-06-16T22:03:58.636-0300] {processor.py:157} INFO - Started process (PID=57312) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:03:58.639-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:03:58.642-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:03:58.641-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:03:58.701-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:03:58.689-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:03:58.701-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:03:58.701-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:03:58.702-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:03:58.748-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2025-06-16T22:05:10.862-0300] {processor.py:157} INFO - Started process (PID=57557) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:05:10.864-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:05:10.867-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:05:10.866-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:05:10.927-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:05:10.914-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:05:10.928-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:05:10.928-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:05:10.929-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:05:10.979-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2025-06-16T22:06:23.568-0300] {processor.py:157} INFO - Started process (PID=57769) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:06:23.572-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:06:23.575-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:06:23.574-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:06:23.640-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:06:23.629-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:06:23.642-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:06:23.641-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:06:23.643-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:06:23.698-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.140 seconds
[2025-06-16T22:07:34.712-0300] {processor.py:157} INFO - Started process (PID=57982) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:07:34.714-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:07:34.715-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:07:34.715-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:07:34.763-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:07:34.754-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:07:34.764-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:07:34.764-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:07:34.765-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:07:34.802-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2025-06-16T22:08:49.010-0300] {processor.py:157} INFO - Started process (PID=58326) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:08:49.012-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:08:49.013-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:08:49.013-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:08:49.053-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:08:49.046-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:08:49.054-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:08:49.054-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:08:49.055-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:08:49.095-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2025-06-16T22:09:54.467-0300] {processor.py:157} INFO - Started process (PID=58520) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:09:54.469-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:09:54.471-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:09:54.471-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:09:54.524-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:09:54.513-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:09:54.525-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:09:54.524-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:09:54.526-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:09:54.571-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2025-06-16T22:10:59.189-0300] {processor.py:157} INFO - Started process (PID=58717) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:10:59.191-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:10:59.193-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:10:59.193-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:10:59.232-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:10:59.225-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:10:59.232-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:10:59.232-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:10:59.233-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:10:59.270-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2025-06-16T22:11:57.862-0300] {processor.py:157} INFO - Started process (PID=58892) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:11:57.864-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:11:57.866-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:11:57.865-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:11:57.908-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:11:57.900-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:11:57.909-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:11:57.908-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:11:57.909-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:11:57.947-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2025-06-16T22:12:56.621-0300] {processor.py:157} INFO - Started process (PID=59075) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:12:56.623-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:12:56.625-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:12:56.624-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:12:56.669-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:12:56.662-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:12:56.670-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:12:56.670-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:12:56.671-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:12:56.704-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2025-06-16T22:14:04.255-0300] {processor.py:157} INFO - Started process (PID=59273) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:14:04.259-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:14:04.260-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:14:04.260-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:14:04.301-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:14:04.294-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:14:04.302-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:14:04.302-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:14:04.303-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:14:04.334-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2025-06-16T22:15:12.804-0300] {processor.py:157} INFO - Started process (PID=59479) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:15:12.806-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:15:12.808-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:15:12.807-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:15:12.857-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:15:12.848-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:15:12.858-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:15:12.858-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:15:12.859-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:15:12.900-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2025-06-16T22:16:25.086-0300] {processor.py:157} INFO - Started process (PID=59816) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:16:25.087-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:16:25.089-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:16:25.089-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:16:25.131-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:16:25.123-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:16:25.132-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:16:25.132-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:16:25.133-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:16:25.176-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2025-06-16T22:17:30.636-0300] {processor.py:157} INFO - Started process (PID=60019) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:17:30.639-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:17:30.642-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:17:30.641-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:17:30.703-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:17:30.693-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:17:30.704-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:17:30.704-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:17:30.705-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:17:30.752-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.121 seconds
[2025-06-16T22:18:56.912-0300] {processor.py:157} INFO - Started process (PID=60264) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:18:56.915-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:18:56.917-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:18:56.916-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:18:56.977-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:18:56.965-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:18:56.978-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:18:56.978-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:18:56.979-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:18:57.026-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.121 seconds
[2025-06-16T22:20:22.457-0300] {processor.py:157} INFO - Started process (PID=60509) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:20:22.459-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:20:22.462-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:20:22.461-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:20:22.525-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:20:22.514-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:20:22.526-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:20:22.525-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:20:22.527-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:20:22.573-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2025-06-16T22:21:43.459-0300] {processor.py:157} INFO - Started process (PID=60742) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:21:43.461-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:21:43.464-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:21:43.463-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:21:43.527-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:21:43.515-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:21:43.528-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:21:43.528-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:21:43.529-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:21:43.583-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.131 seconds
[2025-06-16T22:23:05.488-0300] {processor.py:157} INFO - Started process (PID=60977) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:23:05.490-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:23:05.493-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:23:05.492-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:23:05.549-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:23:05.538-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:23:05.550-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:23:05.550-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:23:05.550-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:23:05.596-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2025-06-16T22:24:31.502-0300] {processor.py:157} INFO - Started process (PID=61343) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:24:31.504-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:24:31.507-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:24:31.506-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:24:31.564-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:24:31.553-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:24:31.565-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:24:31.564-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:24:31.566-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:24:31.610-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2025-06-16T22:25:49.776-0300] {processor.py:157} INFO - Started process (PID=61572) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:25:49.780-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:25:49.783-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:25:49.782-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:25:49.847-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:25:49.835-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:25:49.848-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:25:49.848-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:25:49.849-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:25:49.901-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.134 seconds
[2025-06-16T22:27:11.817-0300] {processor.py:157} INFO - Started process (PID=61802) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:27:11.820-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:27:11.822-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:27:11.821-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:27:11.889-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:27:11.877-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:27:11.891-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:27:11.890-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:27:11.891-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:27:11.944-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.134 seconds
[2025-06-16T22:28:30.193-0300] {processor.py:157} INFO - Started process (PID=62027) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:28:30.197-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:28:30.200-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:28:30.199-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:28:30.264-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:28:30.253-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:28:30.265-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:28:30.265-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:28:30.267-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:28:30.324-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.140 seconds
[2025-06-16T22:29:50.579-0300] {processor.py:157} INFO - Started process (PID=62259) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:29:50.581-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:29:50.584-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:29:50.583-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:29:50.645-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:29:50.633-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:29:50.646-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:29:50.646-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:29:50.647-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:29:50.694-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.122 seconds
[2025-06-16T22:31:04.013-0300] {processor.py:157} INFO - Started process (PID=62474) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:31:04.016-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:31:04.019-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:31:04.018-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:31:04.081-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:31:04.070-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:31:04.083-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:31:04.082-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:31:04.083-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:31:04.133-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2025-06-16T22:32:48.391-0300] {processor.py:157} INFO - Started process (PID=62850) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:32:48.394-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-16T22:32:48.396-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:32:48.395-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:32:48.447-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:32:48.438-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-16T22:32:48.448-0300] {logging_mixin.py:154} INFO - [2025-06-16T22:32:48.448-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-16T22:32:48.449-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-16T22:32:48.487-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2025-06-17T20:50:59.160-0300] {processor.py:157} INFO - Started process (PID=63667) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:50:59.163-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-17T20:50:59.166-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:50:59.165-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:50:59.236-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:50:59.224-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-17T20:50:59.237-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:50:59.236-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-17T20:50:59.238-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:50:59.291-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2025-06-17T20:52:23.544-0300] {processor.py:157} INFO - Started process (PID=63870) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:52:23.546-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-17T20:52:23.548-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:52:23.547-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:52:23.599-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:52:23.589-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-17T20:52:23.600-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:52:23.600-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-17T20:52:23.601-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:52:23.646-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2025-06-17T20:53:44.311-0300] {processor.py:157} INFO - Started process (PID=64220) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:53:44.314-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-17T20:53:44.316-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:53:44.316-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:53:44.366-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:53:44.358-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-17T20:53:44.367-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:53:44.367-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-17T20:53:44.368-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:53:44.409-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.105 seconds
[2025-06-17T20:54:52.043-0300] {processor.py:157} INFO - Started process (PID=64414) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:54:52.046-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-17T20:54:52.047-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:54:52.047-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:54:52.083-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:54:52.076-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-17T20:54:52.084-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:54:52.084-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-17T20:54:52.084-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:54:52.124-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.086 seconds
[2025-06-17T20:56:05.925-0300] {processor.py:157} INFO - Started process (PID=64629) to work on /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:56:05.927-0300] {processor.py:829} INFO - Processing file /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-17T20:56:05.929-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:56:05.929-0300] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:56:05.969-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:56:05.961-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-17T20:56:05.970-0300] {logging_mixin.py:154} INFO - [2025-06-17T20:56:05.970-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-17T20:56:05.971-0300] {processor.py:841} WARNING - No viable dags retrieved from /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-17T20:56:06.011-0300] {processor.py:179} INFO - Processing /mnt/c/Users/arcan/Documents/airflow/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
